name: ft-test

on: pull_request

jobs:
  coding-style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check the coding style
      run: |
          cargo fmt -- --check

  check:
    runs-on: ubuntu-latest
    needs: coding-style

    steps:
    - uses: actions/checkout@v2
    - name: Check testsuite-adaptor
      run: cargo check
    - name: Run Clippy
      run: cargo clippy --all

  build:
    runs-on: ubuntu-latest
    needs: coding-style

    steps:
    - uses: actions/checkout@v2
    - name: Build ft
      run: |
          cargo build

  tests:
    runs-on: ubuntu-latest
    needs: coding-style

    steps:
    - uses: actions/checkout@v2
    - name: Run Tests and Documentation examples
      run: |
          cargo test
          cargo run -- -f tests/ft_for_ft.yml
